# Generated by Django 5.0.7 on 2025-11-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0003_alter_paymentlog_billing_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='current_reading_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='billingrecord',
            name='privious_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
