# Generated by Django 5.0.7 on 2025-11-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0004_billingrecord_current_reading_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingrecord',
            old_name='privious_balance',
            new_name='previous_balance',
        ),
    ]
