# Generated by Django 5.0.7 on 2025-11-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0005_rename_privious_balance_billingrecord_previous_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='current_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
