# Generated by Django 6.0.5 on 2026-06-08 09:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0006_billingrecord_current_amount_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='imei',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='meter',
            name='meter_address',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='PrepaidWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_m3', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('last_known_flow_m3', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('valve_status', models.CharField(default='unknown', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='billing_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ValveCommand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=20)),
                ('reason', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('fengbo_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valve_commands', to='billing_app.meter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmartMeterReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meter_address', models.CharField(db_index=True, max_length=50)),
                ('reading_time', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField()),
                ('total_flow_m3', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('total_flow_raw', models.DecimalField(blank=True, decimal_places=3, max_digits=18, null=True)),
                ('total_flow_unit', models.CharField(blank=True, max_length=20, null=True)),
                ('valve_status', models.CharField(blank=True, max_length=20, null=True)),
                ('battery_voltage_v', models.FloatField(blank=True, null=True)),
                ('csq', models.IntegerField(blank=True, null=True)),
                ('no_water_alarm', models.BooleanField(blank=True, null=True)),
                ('low_battery_alarm', models.BooleanField(blank=True, null=True)),
                ('reverse_alarm', models.BooleanField(blank=True, null=True)),
                ('water_temperature_c', models.FloatField(blank=True, null=True)),
                ('instantaneous_flow', models.IntegerField(blank=True, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_readings', to='billing_app.meter')),
            ],
            options={
                'ordering': ['-reading_time', '-received_at'],
                'indexes': [models.Index(fields=['meter_address', '-reading_time'], name='billing_app_meter_a_325e67_idx')],
            },
        ),
    ]
