# Generated by Django 6.0.5 on 2026-06-08 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0007_meter_imei_meter_meter_address_prepaidwallet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valvecommand',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valvecommand',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
