# Generated by Django 6.0.5 on 2026-06-20 19:01

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0009_smart_meter_reading_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardTerminalTariff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate_per_m3', models.DecimalField(decimal_places=4, max_digits=10)),
                ('pulses_per_m3', models.PositiveIntegerField(default=1000)),
                ('offline_limit_kes', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8)),
                ('charge_mode', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardTerminalWhitelistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_no', models.CharField(max_length=50, unique=True)),
                ('operation', models.PositiveSmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='prepaidwallet',
            name='balance_kes',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.CreateModel(
            name='CardBinding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('card_no', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_binding', to='billing_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CardTerminalDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_number', models.CharField(max_length=50, unique=True)),
                ('iccid', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_app.site')),
            ],
        ),
        migrations.CreateModel(
            name='CardTerminalTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(max_length=60, unique=True)),
                ('card_no', models.CharField(db_index=True, max_length=50)),
                ('mode', models.PositiveSmallIntegerField(choices=[(0, 'Payment'), (1, 'Balance Inquiry')])),
                ('source', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline Upload')], default='online', max_length=10)),
                ('amount_deducted_kes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('volume_consumed_units', models.PositiveIntegerField(default=0)),
                ('balance_after_kes', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('is_successful', models.BooleanField(default=False)),
                ('failure_reason', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_app.customer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing_app.cardterminaldevice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
