# Generated by Django 6.0.5 on 2026-06-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0012_cardbinding_nuomiy_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardbinding',
            name='nuomiy_card_id',
            field=models.CharField(blank=True, help_text='cardId assigned by Nuomiy (used for unsubscribeCard, reissueCard, addrechage)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cardbinding',
            name='nuomiy_customer_id',
            field=models.CharField(blank=True, help_text='customerId assigned by Nuomiy on registration (used for modify/query)', max_length=50, null=True),
        ),
    ]
