# Generated by Django 6.0.5 on 2026-06-29 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0015_card_terminal_topup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CardTerminalTariff',
        ),
    ]
