# Generated by Django 6.0.5 on 2026-06-29 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0016_remove_card_terminal_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatopuprequest',
            name='billing_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_payments', to='billing_app.billingrecord'),
        ),
    ]
