# Generated by Django 6.0.5 on 2026-06-29 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0017_mpesa_topup_billing_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatopuprequest',
            name='topup_type',
            field=models.CharField(choices=[('card_terminal', 'Card Terminal'), ('prepaid', 'Prepaid Smart Meter')], default='card_terminal', max_length=20),
        ),
    ]
