# Generated by Django 6.0.5 on 2026-07-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0018_mpesa_topup_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='backend',
            field=models.CharField(choices=[('FENGBO_POLL', 'Fengbo self-hosted decoder (polls E-Maji for commands)'), ('PREPAIDEMQX', 'Self-hosted prepaid EMQX service (E-Maji pushes commands to it)')], default='FENGBO_POLL', max_length=20),
        ),
    ]
