# Generated by Django 6.0.5 on 2026-07-15 05:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0019_meter_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='meter',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meters', to='billing_app.customer'),
        ),
        migrations.AddField(
            model_name='mpesatopuprequest',
            name='meter',
            field=models.ForeignKey(blank=True, help_text='Set for topup_type=prepaid — which smart meter this top-up credits.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_topups', to='billing_app.meter'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='meter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='billing_app.meter'),
        ),
        migrations.CreateModel(
            name='SmartMeterWallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_m3', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('last_known_flow_m3', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('valve_status', models.CharField(default='unknown', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_wallets', to='billing_app.customer')),
                ('meter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='billing_app.meter')),
            ],
        ),
    ]
