# Generated by Django 6.0.5 on 2026-07-15 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_app', '0021_copy_customer_meter_and_wallet_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='meter',
        ),
        migrations.RemoveField(
            model_name='prepaidwallet',
            name='balance_m3',
        ),
        migrations.RemoveField(
            model_name='prepaidwallet',
            name='last_known_flow_m3',
        ),
        migrations.RemoveField(
            model_name='prepaidwallet',
            name='valve_status',
        ),
    ]
